[component]
structures = [ "content_blocks" ]
label = "Hero Small"
description = "Page hero with the heading, description, buttons, and an image"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
description_html = "<strong>Photographer</strong> and <strong>Visual Content Strategist</strong> from Albany. I work as a lifestyle, product, and landscape photographer, creating images for a diverse range of requests, from online media to printed artwork."
image = "/images/01.jpg"
image_alt = "Vanessa Marley's picture"
